version: 2.1
orbs:
  newman: postman/newman@0.0.2

jobs:
  build:
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - run:
          name: install-dependencies
          command: npm install npm install -S newman-reporter-htmlextra
      - newman/newman-run:
          collection: ./pga.postman_collection.json
          environment: ./graphql.postman_environment.json
          additional-options: -r htmlextra
