version: 2.1
orbs:
  newman: postman/newman@0.0.2
jobs:
  newman-collection-run-env-timeout:
    executor: postman/newman
    steps:
      - checkout
      - newman/newman-run:
          collection: ./pga.postman_collection.json
          environment: ./graphql.postman_environment.json
